apiVersion: v1
kind: Service
metadata:
  labels:
    app: jeedemoliberty
  name: jeedemo-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 9080
  selector:
    app: jeedemoliberty
